git:
  path: github.com/criticalstack/brotop
  branch: master

clone:
  depth: 32767

build:
  normal:
    image: golang:1.9.2-stretch
    commands:
      - go get github.com/tools/godep
      - go get github.com/jteeuwen/go-bindata/...
      - make
      - cat VERSION
    when:
      event: [push]
  dist:
    image: golang:1.9.2-stretch
    commands:
      - go get github.com/tools/godep
      - go get github.com/jteeuwen/go-bindata/...
      - go get github.com/mitchellh/gox
      - make release
    when:
      event: [tag]
publish:
  github_release:
    api_key: $$GITHUB
    files: release/*
    file_exists: fail
    # draft: true
    when:
      event: tag

# image: mephux/docker-golang
# git:
  # path: github.com/criticalstack/brotop
  # branches:
    # - master
# script:
  # - make test
# notify:
  # email:
    # recipients:
      # - $$EMAIL
  # slack:
    # username: $$USERNAME
    # webhook_url: $$WEBHOOK
    # channel: $$CHANNEL
    # on_started: true
    # on_success: true
    # on_failure: true
# publish:
  # github:
    # branch: master
    # script:
      # - make release
    # artifacts:
      # - release
    # tag: v$(cat .Version)
    # token: $$github_token
    # user: criticalstack
    # repo: brotop
